export const sliderItems = [
  {
    id: 1,
    img: "https://img.freepik.com/premium-photo/beautiful-asian-woman-carrying-colorful-bags-shopping-online-with-mobile-phone_8087-3877.jpg",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://i.ibb.co/DG69bQ4/2.png",
    title: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://i.ibb.co/cXFnLLV/3.png",
    title: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "SHIRT STYLE!",
    cat: "Shirts",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    title: "LOUNGEWEAR LOVE",
    cat: "Loungewear",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    title: "LIGHT JACKETS",
    cat: "Jackets",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    price: 10,
    title: "Pink T-shirt",
    desc: "Casual and Simple Wear ",
    categories: ["Shirts"],
    size: ["XS", "S", "M", "L", "XL"],
    color: ["pink"],
  },
  {
    id: 2,
    img: "https://fullyfilmy.in/cdn/shop/products/New-Mockups---no-hanger---TShirt-Yellow.jpg?v=1639657077",
    price: 120,
    title: "RRR T-shirt",
    desc: "Exclusive RRR T-Shirt ",
    categories: ["Shirts"],
    size: ["S", "M", "L"],
    color: ["yellow"],
  },
  {
    id: 3,
    img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    price: 500,
    title: "Red Jungle Shirt",
    desc: "Colorful Tourist Beach Shirt",
    categories: ["Shirts"],
    size: ["S", "M", "L"],
    color: ["red"],
  },
  {
    id: 4,
    img: "https://sites.create-cdn.net/siteimages/28/4/9/284928/15/5/5/15554861/876x1000.jpg?1497532423",
    price: 300,
    title: "Black Dress",
    desc: "Amazing Party Dress",
    categories: ["Loungewear"],
    size: ["XS", "S", "M", "L"],
    color: ["black"],
  },
  {
    id: 5,
    img: "https://4.imimg.com/data4/RU/VC/MY-11853389/men-s-jackets.jpg",
    price: 70,
    title: "Bike Jacket",
    desc: "Brown Riding Jacket",
    categories: ["Jackets"],
    size: ["XS"],
    color: ["brown"],
  },
  {
    id: 6,
    img: "https://pbx2-pbww-prod-pbww-cdn.getprintbox.com/media/productimage/e925de22-44e0-4276-bb92-0b4101f5f834/Blank%20Jacket_thumb_900x900",
    price: 900,
    title: "Black Jacket",
    desc: "Sporty Black Jacket",
    categories: ["Jackets"],
    size: ["XS", "S"],
    color: ["black"],
  },
  {
    id: 7,
    img: "https://cdn.media.amplience.net/i/bta/2000549663_99?$product_tile_plp$&$jpg$",
    price: 40,
    title: "Brown Dress",
    desc: "Fashionable Brown Dress",
    categories: ["Loungewear"],
    size: ["XS", "S", "M", "L"],
    color: ["brown"],
  },
  {
    id: 8,
    img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    price: 75,
    title: "White Jacket",
    desc: "Awesome Monsoon Jacket",
    categories: ["Jackets"],
    size: ["M", "L", "XL"],
    color: ["white"],
  },
];

export const users = [
  {
    id: 1,
    name: "Rishikesh",
    username: "Rishi1",
    password: "Rishi1",
  },
];
